# Site settings
title: Pradyumna's CV 
description: pradyumnac's CV
favicon: /assets/img/avatar.JPG
baseurl: https://pradyumnac.github.io/resumecard
url: https://pradyumnac.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-102177899-2

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Pradyumna Chatterjee
  title: Python Developer
  address: Kolkata, India
  email: pady92#gmail[dot]com
  link: https://pradyumnac.github.io
  weibo:
  github: pradyumnac
  linkedin: pradyumnac
  twitter: pradyumnacster
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: XXX Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: XXXXXX University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: English
      proficiency: Professional
    - language2:
      name: Hindi
      proficiency: Professional
    - language3:
      name: German
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: Python
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 80%
    - skill3:
      name: JavaScript
      percentage: 80%
    - skill4:
      name: Google App Engine
      percentage: 50%
    - skill5:
      name: Machine Learning
      percentage: 50%
